name: bank_farming
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_native_splash: ^2.4.6
  carousel_slider: ^5.0.0
  lottie: ^3.3.1
  freezed_annotation: ^3.0.0
  pinput: ^5.0.1
  pin_code_fields: ^8.0.1
  gif: ^2.3.0
  flutter_screenutil: ^5.9.3
  stylish_bottom_bar: ^1.1.1
  curved_labeled_navigation_bar: ^2.0.6
  badges: ^3.1.2
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.4
  hive_ce_generator: ^1.8.2
  freezed: ^3.0.4
  flutter_launcher_icons: ^0.14.3


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/wel_images/
    - assets/images/logo/
    - assets/images/
    - assets/images/animations/
    - assets/images/random/
    - assets/images/categories/
    - assets/images/portrait/
    - assets/images/group/
    - assets/images/feed_image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_native_splash:
  color: "#1F7D53"
  image: assets/images/logo/farm_logo.png
  branding: assets/images/logo/farm_logo.png
  branding_mode: center
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: true

  android_12:
    color: "#1F7D53"
    image: assets/images/logo/farm_logo.png
    branding_mode: center
    android_gravity: center
    ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/farm_logo.png"